kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: alkemio-virtual-contributor-ingest-website-deployment
  labels:
    app: alkemio-virtual-contributor-ingest-website

spec:
  replicas: 1
  selector:
    matchLabels:
      app: alkemio-virtual-contributor-ingest-website
  template:
    metadata:
      labels:
        app: alkemio-virtual-contributor-ingest-website
    spec:
      containers:
        - name: alkemio-virtual-contributor-ingest-website
          image: alkemio.azurecr.io/alkemio-virtual-contributor-ingest-website:latest
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: alkemio-rabbitmq-cluster-default-user
                  key: host
            - name: RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: alkemio-rabbitmq-cluster-default-user
                  key: port
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: alkemio-rabbitmq-cluster-default-user
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: alkemio-rabbitmq-cluster-default-user
                  key: password
            - name: RABBITMQ_QUEUE
              value: virtual-contributor-ingest-website

          envFrom:
            - secretRef:
                name: alkemio-secrets
            - configMapRef:
                name: alkemio-config
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: virtual-contributor-ingest-website-persistent-storage
              mountPath: /app/data
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: virtual-contributor-ingest-website-persistent-storage
          persistentVolumeClaim:
            claimName: virtual-contributor-ingest-website-pv-claim
